version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            ./generate-config > generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml
  say-goodbye1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"
  say-goodbye2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"
  say-goodbye3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"
  say-goodbye4:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"
  say-goodbye5:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"
  say-goodbye6:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"
  say-goodbye7:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBye"
          command: "echo Hi, Goodbye!"

workflows:
  setup:
    jobs:
      - setup
      - say-goodbye1
      - say-goodbye2
      - say-goodbye3
      - say-goodbye4
      - say-goodbye5
      - say-goodbye6
      - say-goodbye7