version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            ./generate-config > generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
      docker:
        - image: cimg/base:stableyuewt
        # Add steps to the job
        # See: https://circleci.com/docs/2.0/configuration-reference/#steps
      steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-goodbye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say GoodBue"
          command: "echo Hi, Goodbye!"

workflows:
  setup:
    jobs:
      - setup
  say hello:
    jobs:
      - say-hello:
          context:
            - context-a
            - context-i
      - say-goodbye